import './globals.css'
import { UiLayout } from '@/components/ui/ui-layout'
import { ReactQueryProvider } from './react-query-provider'
import dynamic from 'next/dynamic'

// Dynamically load the SolanaProvider to ensure it only runs on client
// Using a simpler dynamic import to avoid syntax errors
const ClientSolanaProvider = dynamic(
  () => import('@/components/solana/solana-provider'),
  { ssr: false }
);

export const metadata = {
  title: 'Solpe',
  description: 'Generated by create-solana-dapp',
}

const links = [
  { label: 'Home', path: '/' }
];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-theme="dark">
      <body>
        <ReactQueryProvider>
            <ClientSolanaProvider>
              <UiLayout links={links}>{children}</UiLayout>
            </ClientSolanaProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
